sudo: required
language: go
services:
  - docker
env:
  global:
  #- REPO=epimelis1/wercker-test-go # repository for Docker Hub
  - REPO=webapp-go #repository for AWS ECR
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
before_install:
  - echo "Start go build..."
  - go build -o www main.go  # build go binaries
  - echo "Start docker build..."
  - docker build -t $REPO -f Dockerfile.scratch .  # build docker image
install:
  - echo "no installs!" # put normal pre-testing installs here
script:
  - echo "no tests!" # put testing scripts here
after_success:
  - echo $REPO
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_COMMIT
  - export COMMIT=${TRAVIS_COMMIT::7}
  - echo $COMMIT
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - echo $REPO:$TRAVIS_BRANCH|$TRAVIS_BUILD_NUMBER|$COMMIT
  - docker --version  # document the version travis is using
  #-----------push to Docker hub-------------------------------
  #- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  #- docker tag $REPO $REPO:$TAG
  #- docker tag $REPO $REPO:$TRAVIS_BRANCH-build$TRAVIS_BUILD_NUMBER-$COMMIT
  #- docker push $REPO
  #-----------push to AWS--------------------------------------
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-west-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag $REPO:latest 053029339054.dkr.ecr.us-west-2.amazonaws.com/$REPO:latest
  - docker tag $REPO:latest 053029339054.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BRANCH-build$TRAVIS_BUILD_NUMBER-$COMMIT
  - docker push 053029339054.dkr.ecr.us-west-2.amazonaws.com/$REPO:latest

#-------------------------------------------------
# - export REPO=epimelis1/wercker-test-go
# - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# - docker push epimelis1/wercker-test-go
