sudo: required
language: go
services:
  - docker
env:
  global:
  - REPO=epimelis1/wercker-test-go
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
before_install:
  - go build -o www main.go
  - docker build -t $REPO -f Dockerfile.scratch .
after_success:
  - echo $REPO
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_COMMIT
  - echo $COMMIT
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latestMaster"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG  
  #-----------push to Docker hub-------------------------------
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO

# - export REPO=epimelis1/wercker-test-go
# - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# - docker tag epimelis1/wercker-test-go epimelis1/wercker-test-go:zzz2
# - docker push epimelis1/wercker-test-go
