sudo: required
language: go
services:
  - docker
before_install:
  - docker build -t epimelis1/wercker-test-go -f Dockerfile.scratch .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push epimelis1/wercker-test-go
